{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.astrapi69",
    "module": "jobj-contract-verifier",
    "version": "5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jobj-contract-verifier-5.jar",
          "url": "jobj-contract-verifier-5.jar",
          "size": 18674,
          "sha512": "2bf5abf4f1a32575e08d9adb7807b0a2553f29f6f15eddc2bd9f5a9b2bdc04571aae772b2254780b1ed582f9ca49c69d2ac2c8c8c704bcddfffddaca182863b8",
          "sha256": "a4e52cc45bcef3fb87bf1ba1069b0e567ed06f251d5c8bf176d45c276fe1c95d",
          "sha1": "742a8d12738363a4e1f0a586b965297e16a9e88c",
          "md5": "d0502ec99030210a14e15fff5aebbebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jobj-contract-verifier-5.jar",
          "url": "jobj-contract-verifier-5.jar",
          "size": 18674,
          "sha512": "2bf5abf4f1a32575e08d9adb7807b0a2553f29f6f15eddc2bd9f5a9b2bdc04571aae772b2254780b1ed582f9ca49c69d2ac2c8c8c704bcddfffddaca182863b8",
          "sha256": "a4e52cc45bcef3fb87bf1ba1069b0e567ed06f251d5c8bf176d45c276fe1c95d",
          "sha1": "742a8d12738363a4e1f0a586b965297e16a9e88c",
          "md5": "d0502ec99030210a14e15fff5aebbebf"
        }
      ]
    }
  ]
}
